str1 = raw_input("Enter first string:")
str2 = raw_input("Enter second string:")
str3 = str(str1) + " " + str(str2)
print(str3)
print("Concatenated strings")
print(str3.upper())
print("Str3 in upper case")
print(str3.lower())
print("Str3 in lower case")
temp = str1.split(' ')
print(temp)
print("Splitted strings")
str4 = ' '.join(temp)
print(str4)
print("Joined Strings")
print str4.center(30, '$')
print("Padded strings")